### PR TITLE
Annett inclusion

### PR DESCRIPTION
**Pull request by annett-djpr**
Three new functions to replicate a title/map/bar chart on the Inclusion page to show Vic Youth unemp_rate / part_rate / emp_pop via drop down box.
- [x] title_youth_unemp_emppop_partrate_vic()
- [x] map_youth_unemp_emppop_partrate_vic()
- [x] viz_gr_youth_unemp_emppop_partrate_bar()

- [x] need to add drop down menu

### CODE REVIEW

**Comment by annett-djpr** [comment]
I tried fixing the issue with the failed r cmd check, but can't figure it out - need help.

**Comment by MattCowgill** [comment]
I've fixed the issues with `R CMD check`. 

However, at least one of your functions isn't working for me - `title_youth_unemp_emppop_partrate_vic()` throws an error.

**Comment by MattCowgill** [comment]
@annett-djpr I've marked this pull request as a 'draft'. Please click 'Ready for review' when it's ready for review.

**Comment by annett-djpr** [comment]
Last function to be added to inclusion, viz_gr_youth_vicaus_line() now done and working fine. 

Need to add drop-down box for unemp_rate, part_rate and emp_pop. 

R CMD check passed without any warnings or errors.

**Comment by MattCowgill** [comment]
is this ready for review, @annett-djpr ?

**Comment by MattCowgill** [comment]
Status as at 17 August: 

1. The three `*_youth_unemp_emppop_partrate_vic()` functions have been added to the dashboard in a new focus box at the bottom of the `Youth` section of the `Inclusion` page 
2. The `viz_gr_youth_vicaus_line()` function is good, but the result is a little cluttered. I posted three options to Teams and am awaiting team discussion prior to making changes.

**Comment by MattCowgill** [comment]
Status as at 20 August: 
`viz_gr_youth_vicaus_line()` added to dashboard with checkboxes to reduce clutter.

**Comment by annett-djpr** [comment]
Looks good. Just added % to tooltip, seems to be working fine. Ready for PR.

**Comment by annett-djpr** [comment]
Please review PR when you get a chance. This is ready to go now.

**Pull request merged**
