### PR TITLE
Issue157 redo u iserver files

### PR DESCRIPTION
**Pull request by annett-djpr**
Issue 157. I have rewritten all the page_... files to also include the server code bits. I have created a labour_server.R file and moved other UI and server bits around to make it work like the trade dashboard. The result is exactly as it was, except it is cleaner in the way it is coded. No more 2000+ lines of code in the labour_app.R file. Should make it easier to amend and extend and less prone to us making errors.

The cmd_check fails but I'm pretty sure that's the same for dev and not due to my changes. We should clean that up.

Checklist
----

All PRs:
* [x] Rebase to latest dev branch: `git rebase -i dev`
* [x] Run [styler](https://styler.r-lib.org/) to apply consistent code formatting

New/changed charts:
* [x] Re-generate `app-cache` files by running the server and clicking to the new charts
  - [x]  Delete old cache if modifying an existing chart (or changes won't take hold)
* [x] Menu location: entire dashboard
* [ ] Screenshot attached: looks exactly the same, just the way it works under the hood is more like the tradedashboard

### CODE REVIEW

**Comment by annett-djpr** [comment]
PR issued.

**Comment by Henry-DJPR** [comment]
Fixing tests. One test assumed every page_file only contained UI functions

**Comment by Henry-DJPR** [comment]
Tests still failing. Not because we've done anything wrong - it can't set up the instance anymore☹

**Comment by mrjoh3** [comment]
> Tests still failing. Not because we've done anything wrong - it can't set up the instance anymore☹

let me know if you need help with this

**Pull request merged**
